---

- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present

- name: Generate configuration
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: "{{ nftables_configuration_file }}"
    mode: '0644'
    owner: root
    group: root
  notify: Reload nftables

- name: Nftables service
  ansible.builtin.service:
    name: nftables
    state: "{{ nftables_service_state }}"
    enabled: "{{ nftables_service_enabled }}"
